### PR TITLE
Performance: change user interface to reduce allocs

### PR DESCRIPTION
**Pull request by ShimmerGlass**
The previous implementation, while user friendly, required a lot of
allocations on the hot path. This changes it for an iterator based
implementation that, along with a few smaller optimization, reduces the
allocs by 82% and improves latency by 25%.

Benchmarks comparison:
```
benchmark           old ns/op     new ns/op     delta
BenchmarkSPOE-6     32842         24653         -24.93%

benchmark           old allocs     new allocs     delta
BenchmarkSPOE-6     23             6              -73.91%

benchmark           old bytes     new bytes     delta
BenchmarkSPOE-6     1079          193           -82.11%

```

This branch is based on `timeouts` for convenience. I'll rebase it afterwards.

### CODE REVIEW

**Review by pierresouchay — COMMENTED** [review]
How do you plan to introduce this breaking change?
Do you plan a major version?

**Comment by ShimmerGlass** [comment]
@pierresouchay, ya there is no version currently for this lib. I'm planning on releasing v1.0.0 after these two are merged

**Comment by pierresouchay** [comment]
@ShimmerGlass There are confllicts

**Comment by ShimmerGlass** [comment]
@pierresouchay rebased

**Pull request merged**
